/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lib_view_player_VideoKey */

#ifndef _Included_com_lib_view_player_VideoKey
#define _Included_com_lib_view_player_VideoKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lib_view_player_VideoKey
 * Method:    getVidesoKeyFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_view_player_EncryptKey_getVidesoKeyFromJni
  (JNIEnv *, jclass);
/*
 * Class:     com_lib_view_player_VideoKey
 * Method:    getVidesoKeyFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_view_player_EncryptKey_getSecretKeyFromJni
  (JNIEnv *, jclass);/*
 * Class:     com_lib_view_player_VideoKey
 * Method:    getVidesoKeyFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_view_player_EncryptKey_getSecretWebKeyFromJni
  (JNIEnv *, jclass);
/*
 * Class:     com_lib_view_player_EncryptKey
 * Method:    getWxpayId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_view_player_EncryptKey_getWxpayId
        (JNIEnv *, jclass);
/*
 * Class:     com_lib_view_player_EncryptKey
 * Method:    getWxLogId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_view_player_EncryptKey_getWxLogId
        (JNIEnv *, jclass);
/*
 * Class:     com_lib_view_player_EncryptKey
 * Method:    getWechatScreetMetaValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lib_view_player_EncryptKey_getWechatScreetMetaValue
        (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
